version: '2'
services:
    scrappy-app:
        image: scrappy
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://scrappy-mysql:3306/scrappy?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    scrappy-mysql:
        extends:
            file: mysql.yml
            service: scrappy-mysql
